[theme]
# Primary accent color for interactive elements.
primaryColor = "#d36682"

# Background color for the main content area.
backgroundColor = "#002b36"


# Color used for almost all text.
textColor = "#fff"
